jenkins:
  systemMessage: "Jenkins configured using CasC - mm3!"
  numExecutors: 0
  mode: NORMAL
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: letme1n2
       - id: newuser
         password: newuser
  myViewsTabBar: "standard"
  primaryView:
    all:
      name: "all"
  projectNamingStrategy:
    pattern:
      description: "My naming strategy"
      forceExistingJobs: false
      namePattern: ".*"
  clouds:
    - kubernetes:
        templates:
          - name: "maven-jdk11"
            label: "maven-jdk11"
            nodeUsageMode: EXCLUSIVE
            containers:
              - name: "maven"
                image: "maven:3-jdk-11-openj9"
                alwaysPullImage: true
                workingDir: "/home/jenkins"
                ttyEnabled: true
                resourceRequestCpu: "500m"
                resourceLimitCpu: "1000m"
                resourceRequestMemory: "2Gi"
                resourceLimitMemory: "2Gi"

unclassified:
  globalLibraries:
    libraries:
    - defaultVersion: "master"
      implicit: true
      name: "jpl-podtemplates"
      retriever:
        modernSCM:
          scm:
            git:
              remote: "https://github.com/joostvdg/jpl-podtemplates.git"
              traits:
              - cloneOptionTrait:
                  extension:
                    depth: 1
                    noTags: true
                    shallow: true
    - defaultVersion: "master"
      implicit: true
      name: "jpl-core"
      retriever:
        modernSCM:
          scm:
            git:
              remote: "https://github.com/joostvdg/jpl-core.git"
              traits:
              - cloneOptionTrait:
                  extension:
                    depth: 1
                    noTags: true
                    shallow: true
    - defaultVersion: "master"
      implicit: true
      name: "jpl-maven"
      retriever:
        modernSCM:
          scm:
            git:
              remote: "https://github.com/joostvdg/jpl-maven.git"
              traits:
              - cloneOptionTrait:
                  extension:
                    depth: 1
                    noTags: true
                    shallow: true
  
jobs:
  - script: >
      folder('testjobs')
  - script: >
      pipelineJob('testjobs/maven-agent') {
        definition {
          cps {
            script("""\
              pipeline {
                agent { label 'maven-jdk11' } 
                stages {
                  stage ('test maven') {
                    steps {
                      echo "hello"
                      container('maven') {
                        sh 'mvn version'
                      }
                    }
                  }
                }
              }""".stripIndent())
          }
        }
      }
